// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/palette/CurrentGreen.tsx": () => import("../components/mockups/palette/CurrentGreen.tsx"),
  "./components/mockups/palette/DeepNavy.tsx": () => import("../components/mockups/palette/DeepNavy.tsx"),
  "./components/mockups/palette/TealMint.tsx": () => import("../components/mockups/palette/TealMint.tsx"),
  "./components/mockups/palette/WarmOrange.tsx": () => import("../components/mockups/palette/WarmOrange.tsx")
};
